### ISSUE TITLE
Я знаю. Модули. Описание модуля ответов.

### ISSUE THREAD

**Issue by Shelni09** [educorg/studwork-qa-test#29]
### **Задача:**

Необходимо описать модуль ответов для проекта "Я знаю". 
Т.к. в Notion "закончились блоки", до обновления тарифного плана, предлагаю использовать google docs. Ссылку на документ вставлять в файл с модулями в Notion. После согласования перехода на платный тариф, я перенесу содержимое в Notion,

**Comment by alyldas** [comment]
https://docs.google.com/document/d/1fdWLbe2OoJMDaBbmic7j0p6XJeQqQBnBx1uZBnS0Ugo/edit?usp=sharing

[solutions.md](https://github.com/educorg/studwork-qa-test/files/12782304/solutions.md)

**Comment by Shelni09** [comment]
Отличная работа, @alyldas !
