### ISSUE TITLE
Я знаю. Модули. Описание модуля "E-mail рассылка"

### ISSUE THREAD

**Issue by Shelni09** [educorg/studwork-qa-test#30]
### **Задача:**

Необходимо описать модуль E-mail рассылок для проекта "Я знаю".
Логика описания произвольная, но Ваши коллеги должны понимать "как это работает".
Т.к. в Notion "закончились блоки", до обновления тарифного плана, предлагаю использовать google docs. Ссылку на документ вставлять в файл с модулями в Notion. После согласования перехода на платный тариф, я перенесу содержимое в Notion,

**Comment by alyldas** [comment]
https://docs.google.com/document/d/1RPov0ptLWVdNLapNTQKMfvnaQT_bOpaQaP2h5peF-yc/edit?usp=sharing

[mail.md](https://github.com/educorg/studwork-qa-test/files/12784224/mail.md)
