### ISSUE TITLE
Я знаю. Модули. Описание модулей "Парсеры" и "Файлы и Антивирус".

### ISSUE THREAD

**Issue by Shelni09** [educorg/studwork-qa-test#32]
### **Задача:**

Необходимо описать модули "Парсеры" и "Файлы и Антивирус" для проекта "Я знаю".
Т.к. в Notion "закончились блоки", до обновления тарифного плана, предлагаю использовать google docs. Ссылку на документ вставлять в файл с модулями в Notion. После согласования перехода на платный тариф, я перенесу содержимое в Notion,

**Comment by alyldas** [comment]
### Парсеры

https://docs.google.com/document/d/1xuKaTupdpdoMZNSRymkGRNt4QPmU9n6VDymf4BZMf2o/edit?usp=sharing

[parsers.md](https://github.com/educorg/studwork-qa-test/files/12801954/parsers.md)

### Файлы

https://docs.google.com/document/d/1RYvAxTPxjMg07SovnmyMPUxLBKjTfM5gedKnmo2gGew/edit?usp=sharing

[files.md](https://github.com/educorg/studwork-qa-test/files/12803430/files.md)

### Антивирус

https://docs.google.com/document/d/10WM5gjGqxUXGcNheWE3zfiqLhwjw9IFP3Yh5j3f763k/edit?usp=sharing

[virus.md](https://github.com/educorg/studwork-qa-test/files/12803423/virus.md)

**Comment by Shelni09** [comment]
Андрей, молодец! Просто пушка!
