### ISSUE TITLE
Я знаю. Модули. Описание модулей "Платежный модуль" и "Модуль поиска".

### ISSUE THREAD

**Issue by Shelni09** [educorg/studwork-qa-test#33]
### **Задача:**

Необходимо описать модули "Платежный модуль" и "Модуль поиска" для проекта "Я знаю".
Т.к. в Notion "закончились блоки", до обновления тарифного плана, предлагаю использовать google docs. Ссылку на документ вставлять в файл с модулями в Notion. После согласования перехода на платный тариф, я перенесу содержимое в Notion.

**Comment by alyldas** [comment]
По платёжке не до конца понятно как и что описывать, т.к. @Stranger7 переписал реализацию и добавил интеграцию с Tinkoff

**Comment by alyldas** [comment]
https://docs.google.com/document/d/1nOq0j3FaZlFm1Kl09M2LqHYNIbbMYAar8oln-4d2gVs/edit?usp=sharing
[search.md](https://github.com/educorg/studwork-qa-test/files/12843690/search.md)
