### ISSUE TITLE
Я знаю. Модули. Описание платежного модуля.

### ISSUE THREAD

**Issue by Shelni09** [educorg/studwork-qa-test#35]
### **Задача:**

Необходимо описать модуль платежки для проекта "Я знаю".
Т.к. в Notion "закончились блоки", до обновления тарифного плана, предлагаю использовать google docs. Ссылку на документ вставлять в файл с модулями в Notion. После согласования перехода на платный тариф, я перенесу содержимое в Notion.

**Comment by Stranger7** [comment]
https://docs.google.com/document/d/1354KKWIPGrQgRmLhPl3dieVXF1alYIf6qScrKLipeO0/edit?usp=drive_link
