### ISSUE TITLE
Я знаю. Модули. Описание модулей " Юзер + Рейтинг"

### ISSUE THREAD

**Issue by Shelni09** [educorg/studwork-qa-test#39]
### **Задача:**

Необходимо описать модули "Юзер + Рейтинг" для проекта "Я знаю".
Т.к. в Notion "закончились блоки", до обновления тарифного плана, предлагаю использовать google docs. Ссылку на документ вставлять в файл с модулями в Notion. После согласования перехода на платный тариф, я перенесу содержимое в Notion.

**Comment by alyldas** [comment]
### Юзер
https://docs.google.com/document/d/1zrYY2_Ff2Gnp-3qr2DFmseiCVtHvgjFARJTQus8GHKs/edit?usp=sharing
[user.md](https://github.com/educorg/studwork-qa-test/files/12871897/user.md)

### Рейтинг
https://docs.google.com/document/d/1-loiUwdVmTIfveAP76w7ibOcDJ460bNT4W8K3i2CPp0/edit?usp=sharing
[rating.md](https://github.com/educorg/studwork-qa-test/files/12871894/rating.md)
