### ISSUE TITLE
Я знаю. Модули. Работа с описанными модулями.

### ISSUE THREAD

**Issue by Shelni09** [educorg/studwork-qa-test#40]
Для выполнения требуется, чтобы проект был развернут и работала авторизация пользователя.

### **Задача:**

1. В файлах конфигурации роутов найти роуты для текущего модуля
2. Проверить в Postman работоспособность каждого из роутов.
3. При необходимости убрать неиспользуемые поля из запросов/ответов

### **Список модулей:**

- [x] #42
- [x] #43
- [x] #44
- [x] #45
- [x] #46
- [x] #47
- [x] #48
- [x] #49
- [x] #50
- [x] #51
- [x] #52
- [x] #53
- [x] #54

**Comment by Stranger7** [comment]
Авторизация и пользователи
- [x]  POST v1/auth/token авторизация
- [x] GET v1/users
- [x] GET v1/users/count
- [x] POST v1/messages/<userId:\d+>
- [x] GET v1/messages
- [x] GET v1/messages/<userId:\d+>/info
- [x] GET v1/messages/<userId:\d+>
- [x] PATCH v1/messages/<userId:\d+>/read
- [x] GET v1/finance/transactions
- [x] GET v1/finance/payments
- [x] GET v1/finance/hold
- [x] GET v1/finance/hold/administrative
- [x] GET v1/payment/routes
- [x] GET v1/payment/routes/popular
- [x] GET v1/networks/vk/shares
- [x] GET v1/networks/fb/shares
- [x] GET v1/search/complete
- [x] GET v1/search
