### ISSUE TITLE
Язнаю. Модуль Юзера.

### ISSUE THREAD

**Issue by Shelni09** [educorg/studwork-qa-test#42]
Задача:
1. В файлах конфигурации роутов найти роуты для текущего модуля
2. Проверить в Postman работоспособность каждого из роутов.
3. При необходимости убрать неиспользуемые поля из запросов/ответов

https://docs.google.com/document/d/1zrYY2_Ff2Gnp-3qr2DFmseiCVtHvgjFARJTQus8GHKs/edit?usp=sharing

**Comment by alyldas** [comment]
https://docs.google.com/spreadsheets/d/1Rr92lYpXAbz9Ed-oH2-lP9DqIAsXSC6aosakDGKDLxU/edit?usp=sharing

- Почему-то не работает отправка писем (глобально не указываются темы писем).
  Не относится к этой задаче, остальная логика работает
- Нашёл 2 бага в одном ендпоинте
- Авторизацию/регистрацию через соц. сети не проверял
