### ISSUE TITLE
Язнаю Модуль рейтинг.

### ISSUE THREAD

**Issue by Shelni09** [educorg/studwork-qa-test#43]
https://docs.google.com/document/d/1-loiUwdVmTIfveAP76w7ibOcDJ460bNT4W8K3i2CPp0/edit?usp=sharing

**Comment by alyldas** [comment]
Выпилил неиспользуемый рейтинг `stars`.
Поле `user_stats.stars` теперь, **предположительно**, более не используется и его можно выпилить
