### ISSUE TITLE
Язнаю. Модуль ответы.

### ISSUE THREAD

**Issue by Shelni09** [educorg/studwork-qa-test#44]
https://docs.google.com/document/d/1fdWLbe2OoJMDaBbmic7j0p6XJeQqQBnBx1uZBnS0Ugo/edit?usp=sharing

**Comment by alyldas** [comment]
https://docs.google.com/spreadsheets/d/17bDpRSO5CYFoYh1lMJZp7Jl5hwSZWWb22OXc8aGXWt0/edit?usp=sharing

Нашёл пару багов и недоработок
