### ISSUE TITLE
Язнаю. Модуль событий.

### ISSUE THREAD

**Issue by Shelni09** [educorg/studwork-qa-test#46]
https://docs.google.com/document/d/1Z6r7kBT2QhF1wdxr2pB5XlPk1MouCfmtglLChNAofOc/edit?usp=sharing

**Comment by alyldas** [comment]
Событие QA_SOLUTION_CREATED (530, onSolutionCreate) используется только в акте, который используется только в тесте: https://github.com/educorg/qa-back/blob/base/common/scenarios/qa/solution/acts/CreateEvent.php

Все остальные события успешно создаются
