### ISSUE TITLE
Язнаю. Модуль e-mail писем.

### ISSUE THREAD

**Issue by Shelni09** [educorg/studwork-qa-test#47]
https://docs.google.com/document/d/1RPov0ptLWVdNLapNTQKMfvnaQT_bOpaQaP2h5peF-yc/edit?usp=sharing

**Comment by alyldas** [comment]
`sms-provider-low-balance-redsms` view not working

Все остальные методы работают.
Реальные вызовы методов (из бизнес-логики) не проверял.
Неиспользуемые методы убрал ещё давно
