### ISSUE TITLE
Язнаю. Модуль платных услуг.

### ISSUE THREAD

**Issue by Shelni09** [educorg/studwork-qa-test#48]
### **Модуль не описан!**
Необходимо описать модуль. Автовывод.

**Comment by alyldas** [comment]
https://docs.google.com/document/d/1Qk2XdcZKrsVwCHEj0ZFuLlZVgH_Lh8kaavdHRU8lYYo/edit?usp=sharing
[autowithdraw.md](https://github.com/educorg/studwork-qa-test/files/13238970/autowithdraw.md)

**Comment by Shelni09** [comment]
Задача закрыта. Модуль в доке notion
