### ISSUE TITLE
Язнаю. Модуль антивируса.

### ISSUE THREAD

**Issue by Shelni09** [educorg/studwork-qa-test#51]
https://docs.google.com/document/d/10WM5gjGqxUXGcNheWE3zfiqLhwjw9IFP3Yh5j3f763k/edit?usp=sharing

**Comment by alyldas** [comment]
В рамках этого модуля была убрана устаревшая реализация интеграции с VirusTotal. Более логика не изменалась, всё будет работать с правильными данными подключения к ClamAV в .env

В Студворке/Ворке используемая библиотека `xenolope/quahog` была обновлена до 3 версии. Можно пропатчить, там немного изменений
