### ISSUE TITLE
Язнаю. Модуль поиска.

### ISSUE THREAD

**Issue by Shelni09** [educorg/studwork-qa-test#53]
Модуль не описан. Необходимо его описать в Notion.

**Comment by alyldas** [comment]
https://docs.google.com/document/d/1qMFTAXhs1OWa9GY7XtzkTP-BYwXsqL91UbV-ZNIqU3Y/edit?usp=sharing
[search.md](https://github.com/educorg/studwork-qa-test/files/12928543/search.md)
